"""add is_synthetic provenance columns

Revision ID: 920d933cd2f6
Revises: e3134cafaaab
Create Date: 2026-10-09 15:09:59.218503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920d933cd2f6'
down_revision: Union[str, Sequence[str], None] = 'e3134cafaaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    server_default=false backfills every existing row (demo or real) as non-synthetic, so nothing already in
    the database silently disappears from dashboards after this migration runs. Use
    scripts/purge_demo_data.py separately to remove or relabel rows that came from seed.py.
    """
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_alerts_is_synthetic'), ['is_synthetic'], unique=False)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_cases_is_synthetic'), ['is_synthetic'], unique=False)

    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_security_events_is_synthetic'), ['is_synthetic'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_is_synthetic'))
        batch_op.drop_column('is_synthetic')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_is_synthetic'))
        batch_op.drop_column('is_synthetic')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_is_synthetic'))
        batch_op.drop_column('is_synthetic')

    # ### end Alembic commands ###
