"""initial schema

Revision ID: e3134cafaaab
Revises: 
Create Date: 2026-10-09 12:19:17.444537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3134cafaaab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_frameworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('max_assets', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('compliance_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_controls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_controls_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_controls_framework_id'), ['framework_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('slack_webhook_url', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_github_id'), ['github_id'], unique=True)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cpe_string', sa.String(), nullable=True),
    sa.Column('is_ot_asset', sa.Boolean(), nullable=False),
    sa.Column('network_zone', sa.String(), nullable=False),
    sa.Column('primary_protocol', sa.String(), nullable=True),
    sa.Column('last_known_ip', sa.String(), nullable=True),
    sa.Column('criticality', sa.String(), nullable=False),
    sa.Column('discovery_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('mitre_tactics', sa.JSON(), nullable=True),
    sa.Column('mitre_techniques', sa.JSON(), nullable=True),
    sa.Column('attack_narrative', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_user_id'), ['user_id'], unique=False)

    op.create_table('compliance_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('evidence_detail', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assessed_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['compliance_controls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'control_id', name='uq_assessment_user_control')
    )
    with op.batch_alter_table('compliance_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_assessments_user_id'), ['user_id'], unique=False)

    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('rule_content', sa.Text(), nullable=False),
    sa.Column('mitre_techniques', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_rules_user_id'), ['user_id'], unique=False)

    op.create_table('event_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_sources_user_id'), ['user_id'], unique=False)

    op.create_table('hunt_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('queries_run', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('sigma_rule', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hunt_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hunt_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('integration_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_configs_user_id'), ['user_id'], unique=False)

    op.create_table('network_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('target_ip', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('bytes_transferred', sa.BigInteger(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_connections_user_id'), ['user_id'], unique=False)

    op.create_table('network_sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('api_token_hash', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('network_segment', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_discovery_count', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_sensors_user_id'), ['user_id'], unique=False)

    op.create_table('validation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('mitre_techniques', sa.JSON(), nullable=False),
    sa.Column('results_summary', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_runs_user_id'), ['user_id'], unique=False)

    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_run_id'), ['run_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('known_exploited', sa.Boolean(), nullable=False),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('epss_percentile', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_cve_id'), ['cve_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('case_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_timeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_timeline_case_id'), ['case_id'], unique=False)

    op.create_table('discovered_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('device_class', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('ports_open', sa.JSON(), nullable=True),
    sa.Column('services_detected', sa.JSON(), nullable=True),
    sa.Column('protocols', sa.JSON(), nullable=True),
    sa.Column('industrial_protocols', sa.JSON(), nullable=True),
    sa.Column('is_ot_device', sa.Boolean(), nullable=False),
    sa.Column('ot_device_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('discovery_method', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('is_correlated', sa.Boolean(), nullable=False),
    sa.Column('correlation_score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_id'], ['network_sensors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip_address', name='uq_device_user_ip')
    )
    with op.batch_alter_table('discovered_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_devices_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_devices_user_id'), ['user_id'], unique=False)

    op.create_table('response_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('autonomy_level', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_plans_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_plans_user_id'), ['user_id'], unique=False)

    op.create_table('sboms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.Column('vulnerability_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sboms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sboms_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sboms_user_id'), ['user_id'], unique=False)

    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('signature_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('dest_ip', sa.String(), nullable=True),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('bytes_in', sa.Integer(), nullable=True),
    sa.Column('bytes_out', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('processed', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['event_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_user_ts', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_dest_ip'), ['dest_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_source_ip'), ['source_ip'], unique=False)

    op.create_table('validation_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=False),
    sa.Column('technique_name', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('expected_detection', sa.Text(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_steps_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_steps_technique_id'), ['technique_id'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['response_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_plan_id'), ['plan_id'], unique=False)

    op.create_table('case_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_alerts_case_id'), ['case_id'], unique=False)

    op.create_table('case_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['security_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_events_case_id'), ['case_id'], unique=False)

    op.create_table('remediation_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_downtime_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_maintenance_window', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_actions_alert_id'), ['alert_id'], unique=False)

    op.create_table('sbom_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sbom_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('purl', sa.String(), nullable=True),
    sa.Column('cpe', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('hash_sha256', sa.String(), nullable=True),
    sa.Column('vulnerabilities', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sbom_id'], ['sboms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sbom_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sbom_components_sbom_id'), ['sbom_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sbom_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sbom_components_sbom_id'))

    op.drop_table('sbom_components')
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_actions_alert_id'))

    op.drop_table('remediation_actions')
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_events_case_id'))

    op.drop_table('case_events')
    with op.batch_alter_table('case_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_alerts_case_id'))

    op.drop_table('case_alerts')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_plan_id'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('validation_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_steps_technique_id'))
        batch_op.drop_index(batch_op.f('ix_validation_steps_run_id'))

    op.drop_table('validation_steps')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_source_ip'))
        batch_op.drop_index(batch_op.f('ix_security_events_severity'))
        batch_op.drop_index(batch_op.f('ix_security_events_dest_ip'))
        batch_op.drop_index('ix_events_user_ts')

    op.drop_table('security_events')
    with op.batch_alter_table('sboms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sboms_user_id'))
        batch_op.drop_index(batch_op.f('ix_sboms_asset_id'))

    op.drop_table('sboms')
    with op.batch_alter_table('response_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_response_plans_status'))
        batch_op.drop_index(batch_op.f('ix_response_plans_case_id'))

    op.drop_table('response_plans')
    with op.batch_alter_table('discovered_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_devices_ip_address'))

    op.drop_table('discovered_devices')
    with op.batch_alter_table('case_timeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_timeline_case_id'))

    op.drop_table('case_timeline')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_cve_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_asset_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_run_id'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_runs_user_id'))

    op.drop_table('validation_runs')
    with op.batch_alter_table('network_sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_sensors_user_id'))

    op.drop_table('network_sensors')
    with op.batch_alter_table('network_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_connections_user_id'))

    op.drop_table('network_connections')
    with op.batch_alter_table('integration_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_configs_user_id'))

    op.drop_table('integration_configs')
    with op.batch_alter_table('hunt_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hunt_sessions_user_id'))

    op.drop_table('hunt_sessions')
    with op.batch_alter_table('event_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_sources_user_id'))

    op.drop_table('event_sources')
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_rules_user_id'))

    op.drop_table('detection_rules')
    with op.batch_alter_table('compliance_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_assessments_user_id'))

    op.drop_table('compliance_assessments')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_user_id'))
        batch_op.drop_index(batch_op.f('ix_cases_status'))

    op.drop_table('cases')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_user_id'))

    op.drop_table('assets')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_github_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_customer_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('compliance_controls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_controls_framework_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_controls_control_id'))

    op.drop_table('compliance_controls')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    op.drop_table('compliance_frameworks')
    # ### end Alembic commands ###
